#cloud-config

hostname: dns

timezone: Europe/Paris

users:
  - name: devops
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh_authorized_keys:
      - ssh-rsa 
    shell: /bin/bash

package_update: true
package_upgrade: true
packages:
  - dnsmasq

write_files:
  - path: /etc/dnsmasq.conf
    permissions: '0644'
    owner: root:root
    content: |
      address=/gitlab.transporteur.ovh/192.168.0.18
      server=8.8.8.8
      server=1.1.1.1

runcmd:
  - sudo systemctl stop systemd-resolved
  - sudo systemctl disable systemd-resolved
  - echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf
  - sudo systemctl restart dnsmasq