#cloud-config

hostname: gitlab

timezone: Europe/Paris

users:
  - name: devops
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh_authorized_keys:
    shell: /bin/bash

package_update: true
package_upgrade: true
packages:
  - curl
  - openssh-server
  - ca-certificates
  - tzdata
  - perl

runcmd:
  - resolvectl dns eth0 192.168.0.19
  - systemctl restart systemd-resolved
  - echo "postfix postfix/mailname string gitlab.local" | sudo debconf-set-selections
  - echo "postfix postfix/main_mailer_type string 'Internet Site'" | sudo debconf-set-selections
  - sudo DEBIAN_FRONTEND=noninteractive apt install -y postfix
  - curl
    https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    | sudo bash
  - sudo EXTERNAL_URL="gitlab.local.com" apt install -y gitlab-ce