#cloud-config

hostname: vm_cicd

timezone: Europe/Paris

users:
  - name: devops
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: true
    shell: /bin/bash

package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - openjdk-17-jdk
  - maven

network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 192.168.56.3/24

runcmd:
  - wget -O jfrog-deb-installer.tar.gz "https://releases.jfrog.io/artifactory/jfrog-prox/org/artifactory/pro/deb/jfrog-platform-trial-prox/[RELEASE]/jfrog-platform-trial-prox-[RELEASE]-deb.tar.gz"
  - tar -xvzf jfrog-deb-installer.tar.gz
  - cd jfrog-platform-trial-pro*
  - sudo ./install.sh
  - sudo systemctl start artifactory.service
  - sudo systemctl start xray.service
  - sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install jenkins
